# -*- coding: utf-8 -*-
"""download_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17pjNHMCnymK-2Jyomg79SiB07fflmDgs

# **Carga de los datos**
"""

# Librerías a utilizar
from google.colab import drive
import pandas as pd

# Cargar en Colab mi drive para dejar las imágenes procesadas
def mount_drive ():
  drive.mount('/content/drive', force_remount=True)

# Archivos noticias 
def get_data():
  fake_file = '/content/drive/MyDrive/Colab Notebooks/MLOPS/Data/Fake.csv'
  true_file = '/content/drive/MyDrive/Colab Notebooks/MLOPS/Data/True.csv'
  pd_true = pd.read_csv(true_file)
  pd_fake = pd.read_csv(fake_file)
  return pd_true, pd_fake

mount_drive()
news_true, news_fake = get_data()

"""## **Archivo de noticias verdaderas**"""

# Análisis del archivo de noticias verdaderas
news_true.head()

news_true.info()

"""## **Archivo de noticias falsas**"""

news_fake.head()

news_fake.info()